name = "egde-hn-dev"
type = "javascript"
account_id = "efb289061241436254219b424fcea4cf"
workers_dev = true
kv_namespaces = [ 
  { binding = "KV_STORAGE", id = "a713f738814e4de6939b8f9906e01de5", preview_id = "41a0e5dd97134debac212ea90d2d9061" }
]

[vars]
  WORKER_LOCATION = 'http://localhost:8787'
  CF_STORAGE_AREA__DEFAULT_KV_NAMESPACE = 'KV_STORAGE'

[env.staging]
  name = "edge-hn-stage"
  kv_namespaces = [
    { binding = "KV_STORAGE", id = "1b7502d1fe76494b84eb0330dd31f58b" }
  ]

  [env.staging.vars]
    WORKER_LOCATION = 'https://edge-hn-stage.qwtel.workers.dev'
    CF_STORAGE_AREA__DEFAULT_KV_NAMESPACE = 'KV_STORAGE'