name = "news-dev"
main = "./dist/worker.js"
account_id = "efb289061241436254219b424fcea4cf"
workers_dev = true
compatibility_date = "2022-04-05"
compatibility_flags = ["html_rewriter_treats_esi_include_as_void_tag"]

[site]
  bucket = "./public"

[build]
  command = "npm run build"

[vars]
  WORKER_LOCATION = 'http://localhost:8787'

[env.production]
  name = "worker-news"

  [env.production.vars]
    WORKER_LOCATION = 'https://worker-news.qwtel.workers.dev'
