name: Deno Deploy

on:
  push:
    branches: 
      - deno

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2
        with:
          version: 6
          run_install: true
      - run: rm -r node_modules
      - uses: denoland/deployctl@v1
        with:
          project: worker-news
          entrypoint: src/entry/deno.ts
          import-map: import-map.json
      