name: Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy-cf:
    runs-on: ubuntu-latest
    name: Deploy Cloudflare
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true
      - uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: production
  deploy-deno:
    runs-on: ubuntu-latest
    name: Deploy Deno
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true
      - run: rm -r node_modules
      - uses: denoland/deployctl@v1
        with:
          project: worker-news
          entrypoint: src/entry/deno.ts
          import-map: import-map.json
      